Paths:
  Run_name: Conv_test
  Base_dir: /Users/shiki/DATA/HKC_RELATED/ 
  K_src_dir: /Users/shiki/Documents/Documents – Abetharan’s MacBook Pro/Imperial_College_London/Ph.D./SOL-KiT/
  F_src_dir: /Users/shiki/Documents/Documents – Abetharan’s MacBook Pro/Imperial_College_London/Ph.D./HyKiCT/debug/apps/
  Init_path:  /Users/shiki/DATA/HKC_RELATED/init_data/high_res_easier_brodrick_longer_hohlraum
  F_config_path: /Users/shiki/Documents/Documents – Abetharan’s MacBook Pro/Imperial_College_London/Ph.D./HKC_FRAMEWORK/hkc_framework/couple_hykict/config.yml 
  K_config_path: /Users/shiki/Documents/Documents – Abetharan’s MacBook Pro/Imperial_College_London/Ph.D.//HKC_FRAMEWORK/hkc_framework/couple_sol_kit/config.yml
Codes:
  Kinetic_code: sol_kit
  Fluid_code: hykict
Coupling_params:
  Nx: 150
  Cycles: 2
  Eta: 0.1E-2
 
Mode:
  Couple_divq: false
  Couple_multi: false
  Couple_adaptive: false
  Couple_leap_frog: true
  Start_from_kinetic: false 
  Load_f1: true
  Start_coupled: false #Takes precedence over start from kinetic, assumes relevant quanties exist. Does not work with adapative
Misc:
  HDF5: False
  Convergence_monitoring: true
  Zip: false
  Continue: true
  HPC: false 
  Overwrite: true
