Paths:
  Run_name: monitoring_check
  Base_dir: /media/abetharan/DATADRIVE2/Abetharan 
  K_src_dir: /home/abetharan/SOL-KiT/
  F_src_dir: /home/abetharan/HyKiCT/build/apps/
  Init_path: /home/abetharan/HYDRO_KINETIC_COUPLING/ES_Investigation/02_init_data/ 
  F_config_path: /home/abetharan/HKC_FRAMEWORK/hkc_framework/couple_hykict/config.yml 
  K_config_path: /home/abetharan/HKC_FRAMEWORK/hkc_framework/couple_sol_kit/config.yml
Codes:
  Kinetic_code: sol_kit
  Fluid_code: hykict
Coupling_params:
  Nx: 63
  Cycles: 2
  Couple_divq : false
  Couple_multi : false
  Couple_adapative : true
  Start_from_kinetic: true 
Misc:
  Convergence_monitoring: true
  Zip: false
  Continue: false
  HPC: false
  Overwrite: true
