Paths:
  Run_name: gd_hohlraum_test
  Base_dir: /media/Abetharan/ 
  K_src_dir: /home/abetharan/SOL-KiT/
  F_src_dir: /home/abetharan/HyKiCT/debug/apps/
  Init_path:  /media/Abetharan/init_data/gd_hohlraum_hydra_20_0/
  F_config_path: /home/abetharan/HKC_FRAMEWORK/hkc_framework/couple_hykict/config.yml 
  K_config_path: /home/abetharan/HKC_FRAMEWORK/hkc_framework/couple_sol_kit/config.yml
Codes:
  Kinetic_code: sol_kit
  Fluid_code: hykict
Coupling_params:
  Nx: 92
  Cycles: 10
  Eta: 0.1E-2
  hdf5_output_freq: 2
  t_fluid_operator: 0.1E-10
Mode:
  Couple_divq: false
  Couple_multi: true
  Couple_subtract : false
  Couple_adaptive: false
  Couple_leap_frog: false
  Couple_operator_split: false
  Limit_density: true #Limit density to 10x critical
  Start_from_kinetic: true
  Load_f1: true
  Start_coupled: false #Takes precedence over start from kinetic, assumes relevant quanties exist. Does not work with leap-frog
Misc:
  HDF5: true
  Convergence_monitoring: true
  Zip: false
  Continue: true
  HPC: false
  Overwrite: true
