def set_fort_10(tag, val):
    if not 





    kappa = {
    'fo_Cee_on':fo_Cee_on,
    'f1_dt_on':f1_dt_on,
    'fo_dt_on':fo_dt_on,
    'Cee0_iter_on':Cee0_iter_on,
    'initial_cond_on':initial_cond_on,
    'heating_cooling_on':heating_cooling_on,
    'ei_coll_fix_on':ei_coll_fix_on,
    'displ_J_on':displ_J_on,
    'Cee0_Krook_on':Cee0_Krook_on,
    'disable_force_runtime_size_on':disable_force_runtime_size_on,
    'dvfo_centred_diff_on':dvfo_centred_diff_on,
    'dv2f1_centred_diff_on':dv2f1_centred_diff_on,
    'dBdt_centred_diff_on':dBdt_centred_diff_on,
    'Ohmic_Fara_consis_on':Ohmic_Fara_consis_on,
    'Ohmic_all_on':Ohmic_all_on,
    'hydro_on':hydro_on,
    'hydro_fo_on':hydro_fo_on,
    'hydro_f1_on':hydro_f1_on,
    'wpe_over_nuei':wpe_over_nuei,
    'c_over_vte':c_over_vte,
    'atomic_Z':atomic_Z,
    'atomic_A':atomic_A,
    'p_SG':p_SG,
    'q_SG':q_SG,
    'p_SG_init':p_SG_init,
    'nv':nv,
    'nx':nx,
    'ny':ny,
    'dt':dt,
    'tmax':tmax,
    'x_bc_type':x_bc_type,
    'xmin':xmin,
    'xmax':xmax,
    'grid_x_type':grid_x_type,
    'grid_x_ratio':grid_x_ratio,
    'grid_x_alpha':grid_x_alpha,
    'grid_x_offset':grid_x_offset,
    'y_bc_type':y_bc_type,
    'ymin':ymin,
    'ymax':ymax,
    'grid_y_type':grid_y_type,
    'grid_y_ratio':grid_y_ratio,
    'grid_y_alpha':grid_y_alpha,
    'grid_y_offset':grid_y_offset,
    'vmax':vmax,
    'grid_v_type':grid_v_type,
    'grid_v_ratio':grid_v_ratio,
    'grid_v_alpha':grid_v_alpha,
    'grid_v_offset':grid_v_offset,
    'do_user_prof_sub':do_user_prof_sub,
    'prof_Bz_ave':prof_Bz_ave,
    'do_user_heating_sub':do_user_heating_sub,
    'matrix_solver_tol':matrix_solver_tol,
    'nonlin_tol':nonlin_tol,
    'nonlin_itmax':nonlin_itmax,
    'CCee0_00_its_delta': CCee0_00_its_delta,
    'initial_cond_rel_dt': initial_cond_rel_dt,
    'initial_cond_nt': initial_cond_nt,
    'list' : '\n'.join(list)
    }
    return(kappa)