BoundaryConditions:
  Hydro_Right_Boundary: r  
  Rad_Left_Boundary: v
  Rad_Right_Boundary: v 
  Rad_Dirichlet_Left: 0
  Rad_Dirichlet_Right: 0
  Rad_Source_Right: 0
  Rad_Source_Left: 0
FixedParameters:
  nx: 100
  FixedEnergyDensityValue: 0
  FixedOpacityValue: 0
  Frontheat_LastIndex: 0
  Frontheat_StartIndex: 0
  Output_Frequency: 10000
  Preheat_LastIndex: 0
  Preheat_StartIndex: 0
LaserParams:
  Time_Bin: 0.1e-12 #Only relevant if load in laser profile is used. 
  Duration: 0.1e-8 #Always relevant
  Constant_Power: 0.1e11 #If load in laser profile is true this is ignored.
  Wavelength: 0.100e-8
Limiters:
  heatflxlm: 0.05
  prrm: 1.0
  radabm: 1.0
  radbrm: 1.0
  radcmm: 1.0
  raddfm: 1.0
  radesm: 1.0
  radflxlm: 1.0
Output:
  Coordinates: true
  CreateOutputFolder: false
  Exchange: false
  HeatFlow: true
  InternalEnergy: false
  InverseBrem: true
  MassDensity: true
  NumberDensity: true
  PlasmaParameters: false
  Pressure: false
  RadDiffusion: false
  RadEnergyDensity: false
  RadFreeFree: false
  RadPressure: false
  RadTemperature: false
  Temperature: true
  ThermalConduction: true
  Velocity: true
  Viscosity: false
  Zbar: true
Paths:
  FEOS_Path_1: ''
  FEOS_Path_2: ''
  Laser_Profile_Path: ""
  Init_Path: 
  Out_Path: 
Switches:
  AdapativeTimeStep: false
  AdiabaticMode: false
  ConstantCoulombLog: false
  CoupleDivQ: false
  CoupleMulti: false
  Exchange: false
  FullyIonized: true
  HeatConduction: true
  IdealGas: true
  InvBrem: true
  IsothermalMode: false
  LoadInLaserProfile: false
  MultiMaterial: false
  PdVWork: true
  RadDiffusion: false
  RadFreeFree: false
  RadPdVWork: false
  RadiationTransport: false
  SingleTemperature: false
  Velocity: true
  Viscosity: true
TimeParameters:
  ElectronLimit: 0.05
  IonLimit: 0.05
  PVLimit: 0.05
  RadLimit: 0.1
  VolLimit: 0.05
  cfl: 0.85
  dt: 1.0e-15
  dt_max: 1.0e-10
  dt_min: 1.0e-19
  steps: 0
  t_max: 1.0e-12
