BoundaryConditions:
  Hydro_Right_Boundary: r  
  Rad_Left_Boundary: v
  Rad_Right_Boundary: r 
  Rad_Dirichlet_Left: 0
  Rad_Dirichlet_Right: 0
  Rad_Source_Right: 0
  Rad_Source_Left: 0
FixedParameters:
  nx: 92
  ng: 15
  np: 1
  RadNg: 10
  MaxE: 12
  FixedOpacityValue: 0
  Frontheat_LastIndex: 0
  Frontheat_StartIndex: 0
  Output_Frequency: 10000
  Preheat_LastIndex: 0
  Preheat_StartIndex: 0
LaserParams:
  Duration: 23.6e-9 #Always relevant
  Constant_Power: 3.2E19 #If load in laser profile is true this is ignored.
  Wavelength: 0.35E-6 #1E-6 for gold
  Angle: 0
  Albedo: 0
  CriticalLeak: 0.0
  CriticalDumpFraction: 0.01
Limiters:
  heatflxlmE: 0.15
  heatflxlmI: 0.15
  prrm: 1.0
  radabm: 1.0
  radbrm: 1.0
  radcmm: 1.0
  raddfm: 1.0
  radesm: 1.0
  radflxlm: 1.0
  larsen: 2.0
Output:
  Coordinates: true
  CreateOutputFolder: false 
  Exchange: true 
  HeatFlow: true
  InternalEnergy: false
  InverseBrem: true
  MassDensity: true
  NumberDensity: true
  PlasmaParameters: true 
  Pressure: true 
  RadEnergyDensity: true
  RadFreeFree: true
  RadMultiGroupEnergy: true
  RadTemperature: true
  Temperature: true
  ThermalConduction: true
  Velocity: true 
  Viscosity: false
  Zbar: true
Paths:
  #FEOS_Path_1: /Users/shiki/DATA/feos_tables/Cu/Cu
  #FEOS_Path_2: /Users/shiki/DATA/feos_tables/He/He
  FEOS_Path_1: /Users/shiki/DATA/feos_tables/Cu_SpK/Cu
  FEOS_Path_2: /Users/shiki/DATA/feos_tables/He_SpK/He
  Opacity_Path_1: /Users/shiki/DATA/feos_tables/Cu/SPK_MG/
  Opacity_Path_2: /Users/shiki/DATA/feos_tables/He/SPK_MG/
  #Opacity_Path_1: /Users/shiki/DATA/feos_tables/Cu/SPK_Gray/
  #Opacity_Path_2: /Users/shiki/DATA/feos_tables/He/SPK_Gray/
  #Laser_Profile_Path: /Users/shiki/DATA/HKC_RELATED/init_data/Be_planar/laser_profile.txt
  Laser_Profile_Path: /Users/shiki/DATA/HKC_RELATED/init_data/higher_hykict_copper_init/laser_profile.txt
  #Init_Path: /Users/shiki/DATA/HKC_RELATED/init_data/higher_hykict_copper_init/
  Init_Path: /Users/shiki/DATA/HKC_RELATED/init_data/NIC_MG_copper_hohl_18_3ns_init/
  #Init_Path: /Users/shiki/DATA/HKC_RELATED/init_data/new_copper_hohl_snb_init/
  Out_Path: /Users/shiki/DATA/HKC_RELATED/
Switches:
   AdapativeTimeStep: true
   AdiabaticMode: false
   ConstantCoulombLog: false
   CoupleDivQ: false
   CoupleMulti: false
   CoupleOperatorSplit: false
   CoupleSubtract: false
   EoSTables: true 
   Exchange: true
   FullyIonized: false
   HeatConduction: true
   IdealGas: false
   ImplicitHeatConduction: false
   InvBrem: true
   IonizationTables: true
   IsothermalMode: false
   LeakSource: true
   LoadInLaserProfile: true
   LoadInRadEnergy: true
   MultiMaterial: true
   RadDiffusion: true
   RadFreeFree: true
   RadiationTransport: true
   SNBHeatFlow: false 
   SingleTemperature: false
   Velocity: true
   Viscosity: true
TimeParameters:
   AdapativeMethod: 0
   ElectronLimit: 0.005
   IonLimit: 0.005
   PVLimit: 0.01
   RadLimit: 0.005
   VolLimit: 0.01
   cfl: 0.85
   dt: 1.0e-17
   dt_max: 1.0e-12
   dt_min: 1.0e-19
   steps:  0 
   t_init: 0.0e-9
   t_max: 18.3e-9
