BoundaryConditions:
  Hydro_Right_Boundary: f  
  Rad_Left_Boundary: r
  Rad_Right_Boundary: d 
  Rad_Dirichlet_Left: 0
  Rad_Dirichlet_Right: 0
  Rad_Source_Right: 0
  Rad_Source_Left: 0
FixedParameters:
  nx: 92
  ng: 20
  MaxE: 0
  FixedOpacityValue: 0
  Frontheat_LastIndex: 0
  Frontheat_StartIndex: 0
  Output_Frequency: 10000
  Preheat_LastIndex: 0
  Preheat_StartIndex: 0
LaserParams:
  Duration: 2.0e-9 #Always relevant
  Constant_Power: 1.0E18 #If load in laser profile is true this is ignored.
  Wavelength: 0.351E-6 #0.351E-6 for gold
  Angle: 0
  Albedo: 0
  CriticalLeak: 0.01
  CriticalDumpFraction: 0.01
Limiters:
  heatflxlmE: 1.0
  heatflxlmI: 1.0
  prrm: 1.0
  radabm: 1.0
  radbrm: 1.0
  radcmm: 1.0
  raddfm: 1.0
  radesm: 1.0
  radflxlm: 1.0
  larsen: 2.0
Output:
  Coordinates: true
  CreateOutputFolder: false
  Exchange: true 
  HeatFlow: true
  InternalEnergy: false
  InverseBrem: true
  MassDensity: true
  NumberDensity: true
  PlasmaParameters: false 
  Pressure: true 
  RadDiffusion: false
  RadEnergyDensity: true
  RadFreeFree: false
  RadPressure: false
  RadTemperature: true
  Temperature: true
  ThermalConduction: true
  Velocity: true 
  Viscosity: false
  Zbar: true
Paths:
  FEOS_Path_1: /Users/shiki/DATA/feos_tables/Cu/Cu
  FEOS_Path_2: /Users/shiki/DATA/feos_tables/He/He
  Opacity_Path_1: /Users/shiki/DATA/feos_tables/Cu/
  Opacity_Path_2: /Users/shiki/DATA/feos_tables/He/
  Laser_Profile_Path: /Users/shiki/DATA/HKC_RELATED/init_data/copper_hohlraum/laser_profile.txt
  Init_Path: /Users/shiki/DATA/HKC_RELATED/init_data/gd_copper_hohlraum/gd_copper_hohlraum_20_0_reversed/
  Out_Path: /Users/shiki/DATA/
Switches:
  AdapativeTimeStep: false
  AdiabaticMode: false
  ConstantCoulombLog: false
  CoupleDivQ: false
  CoupleMulti: false
  CoupleOperatorSplit: false
  CoupleSubtract: false
  Exchange: false
  FullyIonized: true
  HeatConduction: true
  IdealGas: true
  InvBrem: false
  ImplicitHeatConduction: false
  IsothermalMode: false
  LoadInLaserProfile: false 
  MultiMaterial: false
  RadDiffusion: true
  RadFreeFree: true
  RadPdVWork: false
  RadiationTransport: false 
  SingleTemperature: true 
  SNBHeatFlow: false
  Velocity: true
  Viscosity: true
  EoSTables: false
  IonizationTables: true
  OpacityTables: true
  LoadInRadEnergy: false
TimeParameters:
  ElectronLimit: 0.02
  IonLimit: 0.5
  PVLimit: 0.5
  RadLimit: 0.5
  VolLimit: 0.5
  cfl: 0.85
  dt: 1.0e-17 #5.608e-11
  dt_max: 1.0e-13
  dt_min: 1.0e-16
  steps: 0
  t_max: 0
  t_init: 0
  AdapativeMethod: 0 #0 is BUCKY, >0 HYADES
