Paths:
      Init_Path: "" ##leave empty handled by coupler
      Out_Path: "" #leave empty handled by coupler
      FEOS_Path_1: ""
      FEOS_Path_2: ""
FixedParameters:
      nx: 200
      Rad_Flux_Temperature: 0
      Laser_Wavelength: 100e-9
      Laser_Power: 1e12
      Laser_Dur: 0
      Left_Fluid_Boundary: 0
      Right_Fluid_Boundary: 0
      Left_Rad_Boundary: 2
      Right_Rad_Boundary: 2
      Preheat_StartIndex: 0 #handled internally
      Preheat_LastIndex: 0 #handled internally
      Frontheat_StartIndex: 0 #handled internally
      Frontheat_LastIndex: 0
      Output_Frequency: 1
      FixedOpacityValue: 0
      FixedEnergyDensityValue: 0
TimeParameters:
      dt: 0.1e-12
      dt_max: 0.1e-15 
      dt_min: 0.1e-9
      t_max: 0
      steps: 0 #2
      cfl: 0.85
Limiters:
      heatflxlm: 1.0
      radflxlm: 1.0
      prrm: 1.0
      radabm: 1.0
      radbrm: 1.0
      radcmm: 1.0
      raddfm: 1.0
      radesm: 1.0
Switches:
      Viscosity: true #Artificial Viscosity Include
      Velocity: true #Velocity
      PdVWork: true #pDv Work included in energy update
      HeatConduction: true #Thermal conduction included
      Exchange: false #Exchange between ions and electrons.. basedon NRL 2018
      InvBrem: false #Inverse bremstrahllung i.e. laser. 
      RadiationTransport: false #Radiation Transport 
      RadFreeFree: false #Free-Free Emission
      RadPdVWork: false #Radiatoin PdVwork
      RadDiffusion: false #Ficks diffusion of radation
      IdealGas: true # EoS Ideal gas
      MultiMaterial: false # Multi material
      SingleTemperature: true # Te = Ti
      CoupleDivQ: false # Coupling between kinetic and fluid using div.q
      CoupleMulti: true # Coupling between kinetic and fluid using q/q_sh
      AdapativeTimeStep: false #Adapative time step
      ConstantCoulombLog: false #Coulomb log kept constant which is set above
      FullyIonized: true #Fully ionized
      AdiabaticMode: false # No heat flow
      IsothermalMode: false #Temperature constant
Output:
      CreateOutputFolder: false #Create output folder if not specified
      Coordinates: true
      Viscosity: false
      Velocity: true
      Pressure: false
      MassDensity: true
      NumberDensity: true
      Temperature: true
      Zbar: true
      HeatFlow: true
      ThermalConduction: false
      InternalEnergy: false
      Exchange: false
      InverseBrem: true
      RadFreeFree: false
      RadDiffusion: false
      RadTemperature: false
      RadEnergyDensity: false
      RadPressure: false
      PlasmaParameters: false

