BoundaryConditions:
  Hydro_Right_Boundary: r  
  Rad_Left_Boundary: v
  Rad_Right_Boundary: r 
  Rad_Dirichlet_Left: 0
  Rad_Dirichlet_Right: 0
  Rad_Source_Right: 0
  Rad_Source_Left: 0
FixedParameters:
  nx: 193
  ng: 15
  np: 1
  RadNg: 10
  MaxE: 20
  FixedOpacityValue: 0
  Frontheat_LastIndex: 0
  Frontheat_StartIndex: 0
  Output_Frequency: 2000
  Preheat_LastIndex: 0
  Preheat_StartIndex: 0
  leakMaterial: 1
  leakArea1: 1.5e-5 #7.67596925911667e-06 #06 
  leakArea2: 8.2e-5 #5.279207620861008e-05 #05
LaserParams:
  Duration: 21.7e-9 #Always relevant
  Constant_Power: 3.2E19 #If load in laser profile is true this is ignored.
  Wavelength: 0.351E-6 #1E-6 for gold
  Angle: 0
  Albedo: 0
  CriticalLeak: 0.0
  CriticalDumpFraction: 0.1
  StartIndex: 173
Limiters:
  heatflxlmE: 0.15
  heatflxlmI: 0.15
  prrm1: 1.00
  prrm2: 1.4  #1.5
  radabm: 1.0
  radbrm: 1.0
  radcmm: 1.0
  raddfm: 1.0
  radesm: 1.0
  radflxlm: 0.0
  larsen: 2.0
  sphecamE1: 2.5 
  sphecamI1: 2.5 
  opamP1: 4.8 #5.4
  opamR1: 4.8 #5.4
  sphecamE2: 1.0 
  sphecamI2: 1.0 
  opamP2: 1.0
  opamR2: 1.0
Output:
  Coordinates: true
  CreateOutputFolder: false 
  Exchange: true 
  HeatFlow: true
  InternalEnergy: false
  InverseBrem: true
  MassDensity: true
  NumberDensity: true
  PlasmaParameters: true 
  Pressure: true 
  RadEnergyDensity: true
  RadFreeFree: true
  RadMultiGroupEnergy: true
  RadTemperature: true
  Temperature: true
  ThermalConduction: true
  Velocity: true 
  Viscosity: false
  Zbar: true
Paths:
  FEOS_Path_1: /Users/shiki/DATA/feos_tables/Cu/Cu
  FEOS_Path_2: /Users/shiki/DATA/feos_tables/He/He
  Init_Path: /Users/shiki/DATA/HKC_RELATED/init_data/NIC_hykict_copper_init/
  Laser_Profile_Path: /Users/shiki/DATA/HKC_RELATED/init_data/higher_hykict_copper_init/laser_profile.txt
  Leak_Profile_Path: /Users/shiki/DATA/HKC_RELATED/init_data/higher_hykict_copper_init/leak_profile.txt
  Opacity_Path_1: /Users/shiki/DATA/feos_tables/Cu/SPK_MG/
  Opacity_Path_2: /Users/shiki/DATA/feos_tables/He/SPK_MG/
  Out_Path: /Users/shiki/DATA/HKC_RELATED/

Switches:
   AdapativeTimeStep: true
   AdiabaticMode: false
   ConstantCoulombLog: false
   CoupleDivQ: false
   CoupleMulti: false
   CoupleOperatorSplit: false
   CoupleSubtract: false
   EoSTables: true
   Exchange: true
   FullyIonized: false
   HeatConduction: true
   IdealGas: false
   ImplicitHeatConduction: false
   InvBrem: false
   IonizationTables: true
   IsothermalMode: false
   LeakSource: false
   LoadInLaserProfile: false
   LoadInRadEnergy: false
   MultiMaterial: true
   RadDiffusion: true
   RadFreeFree: true
   RadiationTransport: false
   SNBHeatFlow: false 
   LeeMore: false
   SingleTemperature: false
   Velocity: true
   Viscosity: true
TimeParameters:
   AdapativeMethod: 0
   ElectronLimit: 0.01
   IonLimit: 0.01
   PVLimit: 0.05
   RadLimit: 0.01
   VolLimit: 0.01
   cfl: 0.85
   dt: 1.0e-17
   dt_max: 1.0e-12
   dt_min: 1.0e-19
   steps: 0 
   t_init: 1.11269e-9
   t_max: 7.5e-9
