Norms:
  #NORMALISATION
  Te: 270
  Ne: 8.1E+27
  Z: 36.5
  Ar: 157.5

Params:
  Nx: 0 #handled internally
  Nv: 100
  Np: 1
  Dt: 0.001
  Dx: 0.5
  Dv: 0.0307
  Dv_multi: 1.03
  Nt: 30
  Pre_step_nt: 0
  Pre_step_dt: 0.001
  L_max: 3
  Output_freq: 10

Boundary:
  Periodic: false
  Fixed_up: false
  Fixed_down: false
  No_flow_up: true
  No_flow_down: true

Switches:
  Coll_ei_l: true
  Coll_ee_0: true
  Coll_ee_l: false
  Diag_ee_l: false
  Local_init: false
  Cold_ion_fluid: false
  f_0_maintain: true

Output:
  Density: true
  Temperature: true
  Velocity: false
  E_field: true
  Sh_test: false
